// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package mixxx

import (
	"database/sql"
)

type Crate struct {
	ID           int64
	Name         string
	Count        sql.NullInt64
	Show         sql.NullInt64
	Locked       sql.NullInt64
	AutodjSource sql.NullInt64
}

type CrateTrack struct {
	CrateID int64
	TrackID int64
}

type Library struct {
	ID                   int64
	Artist               sql.NullString
	Title                sql.NullString
	Album                sql.NullString
	Year                 sql.NullString
	Genre                sql.NullString
	Tracknumber          sql.NullString
	Location             sql.NullInt64
	Comment              sql.NullString
	Url                  sql.NullString
	Duration             sql.NullFloat64
	Bitrate              sql.NullInt64
	Samplerate           sql.NullInt64
	Cuepoint             sql.NullInt64
	Bpm                  sql.NullFloat64
	Wavesummaryhex       []byte
	Channels             sql.NullInt64
	DatetimeAdded        sql.NullString
	MixxxDeleted         sql.NullInt64
	Played               sql.NullInt64
	HeaderParsed         sql.NullInt64
	Filetype             sql.NullString
	Replaygain           sql.NullFloat64
	Timesplayed          sql.NullInt64
	Rating               sql.NullInt64
	Key                  sql.NullString
	Beats                []byte
	BeatsVersion         sql.NullString
	Composer             sql.NullString
	BpmLock              sql.NullInt64
	BeatsSubVersion      sql.NullString
	Keys                 []byte
	KeysVersion          sql.NullString
	KeysSubVersion       sql.NullString
	KeyID                sql.NullInt64
	Grouping             sql.NullString
	AlbumArtist          sql.NullString
	CoverartSource       sql.NullInt64
	CoverartType         sql.NullInt64
	CoverartLocation     sql.NullString
	CoverartHash         sql.NullInt64
	ReplaygainPeak       sql.NullFloat64
	Tracktotal           sql.NullString
	Color                sql.NullInt64
	LastPlayedAt         sql.NullTime
	SourceSynchronizedMs sql.NullInt64
}

type Playlist struct {
	ID           int64
	Name         sql.NullString
	Position     sql.NullInt64
	Hidden       int64
	DateCreated  sql.NullTime
	DateModified sql.NullTime
	Locked       sql.NullInt64
}

type PlaylistTrack struct {
	ID              int64
	PlaylistID      sql.NullInt64
	TrackID         sql.NullInt64
	Position        sql.NullInt64
	PlDatetimeAdded sql.NullString
}

type TrackLocation struct {
	ID                int64
	Location          sql.NullString
	Filename          sql.NullString
	Directory         sql.NullString
	Filesize          sql.NullInt64
	FsDeleted         sql.NullInt64
	NeedsVerification sql.NullInt64
}
